#Generates estimated path taken by the user 
#input file is the sorted images csv output file generated by path_estimator.py

import pandas as pd
import folium
import webbrowser
import sys

#function to generate map of the path taken by the user based on the date and time of the images
#Adapted from: https://georgetsilva.github.io/posts/mapping-points-with-folium/

def map_locations(sorted_images):

    df = pd.read_csv(sorted_images)

    # Create a map object centered around the area of interest, Vancouver
    m = folium.Map(location = [49.2827,-123.1207], zoom_start = 12)
    
    # Create a list of latitude and longitude pairs
    locations = df[['lat','lon']]
    list_of_locations = locations.values.tolist()

    # Add markers to the map
    for location in range(len(list_of_locations)):
        folium.Marker(list_of_locations[location], popup = df['location'][location]).add_to(m)
    
    folium.PolyLine(locations, color='red').add_to(m)
    
    #Generate Map
    m.save("path.html")
    webbrowser.open("path.html")